image:
  repository: payments-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8081
  targetPort: 8081
  type: ClusterIP

env:
  DB_URL: "postgresql://user:password@db:5432/payments"
