apiVersion: v1
kind: Service
metadata:
  name: payments-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "payments-service.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
